swagger: "2.0"
info:
  version: 1.0.0
  title: vingle-internship
  description: vingle-internship
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: User
    description: User Endpoint
  - namn: Service
    description: Service Endpoint
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  Service:
    type: object
    title: Service
    required:
      - url
    properties:
      url:
        type: string
        description: url string

  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        description: The example name

paths:    
  /service:
    post:
      tags:
        - Service
      description: generates record of given URL on Database
      parameters:
        - name: service
          in: body
          description: Service Object
          schema:
            $ref: "#/definitions/Service"
    responses:
      201:
        description: Return the url with the specified id
      200:
        description: Already exists, return the data.

  /service/{urlId}:
    get:
      tags:
        - Service
      description: fetch data by specific urlId
    parameters:
        - name: urlId
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
    responses:
      301:
        description: Return the Service with the specified id

  /service/{urlId}/stats:
    get:
      tags:
        - Service
      description: returns stats of record that has given id
    parameters:
        - name: urlId
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
    responses:
      200:
        description: visit count

  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: number of items to skip
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not 

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
